ulg_file: reference.ulg
sample_window: 5
topics:
  vehicle_angular_velocity:
    fields:
      - xyz[0]
      - xyz[1]
      - xyz[2]
  vehicle_rates_setpoint:
    fields:
      - roll
      - pitch
      - yaw
      - thrust_body[2]
  vehicle_acceleration:
    fields:
      - xyz[0]
      - xyz[1]
      - xyz[2]
  battery_status:
    fields:
      - voltage_v
      - voltage_filtered_v
  vehicle_attitude:
    fields:
      - q[0]
      - q[1]
      - q[2]
      - q[3]
