--
-- zuanfeng-deploy auto-sync configuration for lsyncd
-- Generated by setup-sync.sh
--

local device_ip = os.getenv("DEVICE_IP") or "192.168.55.1"
local device_user = os.getenv("DEVICE_USER") or "nv"
local ssh_key = os.getenv("SSH_KEY") or os.getenv("HOME") .. "/.ssh/id_ed25519"
local source_folder = os.getenv("SOURCE_FOLDER") or os.getenv("HOME") .. "/zuanfeng-deploy"
local device_target_folder = os.getenv("DEVICE_TARGET_FOLDER") or "/home/nv/zuanfeng-mono/zuanfeng-deploy"

settings {
    logfile = "/tmp/zuanfeng-sync.log",
    statusFile = "/tmp/zuanfeng-sync.status",
    pidfile = "/tmp/zuanfeng-sync.pid",
    nodaemon = true,
    statusInterval = 10,
}

sync {
    default.rsyncssh,
    source = source_folder .. "/",
    host = device_user .. "@" .. device_ip,
    targetdir = device_target_folder .. "/",
    exclude = {
        ".git/",
        "node_modules/",
        "__pycache__/",
        ".venv/",
        "venv/",
        ".pytest_cache/",
        ".mypy_cache/",
        "*.pyc",
        "*.pyo",
        "*.egg-info",
        ".eggs/",
        "dist/",
        "build/",
        "*.tar",
        "*.tar.gz",
        "*.tar.xz",
        "*.zip",
        ".DS_Store",
        "Thumbs.db",
        ".idea/",
        ".vscode/",
        "*.swp",
        "*.swo",
        "*.log",
        "agent_bins/",
    },
    rsync = {
        archive = true,
        compress = true,
        rsh = "ssh -i " .. ssh_key .. " -o StrictHostKeyChecking=accept-new",
        _extra = { "--delete" },
    },
    delay = 2,
    maxProcesses = 1,
}
